version: 2.1

orbs:
  hello: circleci/hello-build@0.0.10
  
executors:
  lein_exec:
    docker:
      - image: "clojure:lein-2.8.1"
    working_directory: ~/project
    environment:
      MYSPECIALVAR: "my-special-value"
      MYOTHERVAR: "my-other-value"

commands:
  sayhello:
    description: "hello world"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo <<parameters.to>>
      
jobs:
  build:
    executor: lein_exec
    steps:
      - checkout
      - sayhello:
          to: "Lev"
      - hello/hello-triggerer:
          to: "Leo"
  test:
    executor: lein_exec
    environment:
      TESTS: unit
    steps:
      - checkout
      - run: echo "how are you"

workflows:
  "Hello Workflow": 
    jobs:
      - build
      - test
      - hello/hello-build
      
