version: 2.1

orbs:
  hello: circleci/hello-build@0.0.10

commands:
  sayhello:
    description: "hello world"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo <<parameters.to>>
      
jobs:
  hellojob:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - sayhello:
          to: "Lev"

workflows:
  "Hello Workflow": 
    jobs:
      - hellojob
      - hello/hello-build
